version: '3.5'

# This file is an example to build all this images.
# run: docker-compose build

services:
  # Phalcon 3.3 - Debian Buster
  phalcon-3.3-7.2-buster:
    build: images/3.3/debian-buster/apache-php7.2
    image: talentify/phalcon-framework:3.3-php-7.2-apache-buster
    environment:
      - GCC_ARCH=core-avx-i
      - GCC_TUNE=core-avx-i

  # Phalcon 3.4
  phalcon-3.4-7.3:
    build: images/3.4/debian-buster/apache-php7.3
    image: talentify/phalcon-framework:3.4-php-7.3-apache-buster
    environment:
      - GCC_ARCH=core-avx-i
      - GCC_TUNE=core-avx-i
